version: "3.7"
services:
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Default PostgreSQL port is 5432, can get error if using 5432:5432
      - "${POSTGRES_PORT}"

  # Backend
  smartbrain-api:
    container_name: backend
    build: ./
    command: npm start
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - "3000:3000"
